name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'Naveenraj M'

inputs: 
  spec_file:
    description: 'path to the spec file'
    required: true
    default: '*.spec'                     #Any spec file in top 
  additional_repos:
    description: 'A list of repositories to install using yum install'
    required: false
  enable_repos:
    description: 'A list of repositories to enable using yum config-manager --set-enabled'
    required: false
  dockerfile:
    description: 'Choose a different dockerfile [DOES NOT WORK]'
    required: false
    default: 'Dockerfile'

outputs:
  source_rpm_path:
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_content_type:
    description: 'Content-type for Upload'

runs:
  using: 'docker'
  #image: '${{ inputs.dockerfile }}'
  image: 'Dockerfile.alma9'

branding:
  icon: 'package'
  color: 'red'

  
